### ISSUE TITLE
Program pause

### ISSUE THREAD

**Issue by sym330** [tuezato/guided-deep-decoder#1]
The program neither reports errors nor runs, and displays the following：
Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).

**Comment by tuezato** [comment]
You could solve this problem by scaling the input and changing the type. If it doesn't work, could you provide detailed information of errors?

**Comment by sym330** [comment]
The program can continue to run every time I turn off the picture. I used the CMHF in your reference [43] "Multispectral and hyperspectral image fusion by ms/hs fusion net" to generate data. However, when it is put into the network, the PSNR value is getting lower and lower. It seems that there is a problem with MSI. Can you tell how your data set is generated? Thank you very much.The original text is introduced as follows：

- [ ] 
![image](https://user-images.githubusercontent.com/56382939/98456165-fe58e280-21b4-11eb-9821-fb251749886f.png)

**Comment by tuezato** [comment]
LR-HS was generated by averaging HR-HS over 32 x 32 pixel blocks. MSI was generated by applying spectral downsampling to HR-HS on the basis of the spectral response function. Please note that our study used a spectral response function that is different from the function used in [43]. When we apply other methods to our dataset, we firstly need to train the models using the dataset and the same response function with ours and test it using the trained models. I can provide all of the datasets if necessary. Please contact tatsumi.uezato@riken.jp.
