### ISSUE TITLE
change dataset，the PSNR value gets lower and lower, and the training stops automatically

### ISSUE THREAD

**Issue by sym330** [tuezato/guided-deep-decoder#2]
I used my own dataset to generate RGB and low spatial resolution hyperspectral images.the RGB image obtained by multiplying the high resolution hyperspectral image and the spectral response function R, and downsampling the high resolution hyperspectral image to obtain low spatial resolution Rate hyperspectral images. The corresponding spectral response function is changed, but the PSNR value gets lower and lower, and the training stops automatically. I can't find the reason,...

`Iteration 00000    PSNR_HR 9.440 MSE_gap 0.3715181
Iteration 00100    PSNR_HR 14.241 MSE_gap -0.0000244
Iteration 00200    PSNR_HR 14.260 MSE_gap -0.0000003
Iteration 00300    PSNR_HR 14.261 MSE_gap -0.0000000
Iteration 00400    PSNR_HR 14.261 MSE_gap -0.0000000
Iteration 00500    PSNR_HR 14.261 MSE_gap -0.0000000
Iteration 00600    PSNR_HR 14.261 MSE_gap -0.0000000
Iteration 00700    PSNR_HR 14.261 MSE_gap -0.0000000
`
GDD does not require training. I did not perform training but directly applied to other datasets. Does this have any effect?

**Comment by tuezato** [comment]
The experimental setup of your dataset seems to be similar to that of our work. I'm not exactly sure why you get this kind of result. It seems that the optimization is not correctly done.
The method need to use not only the response function but also the downsampling function, which are same with those of your dataset.
Other suggestions are to change the parameters of learning rate (LR) or threshold values and check the changes.

**Comment by sym330** [comment]
The problem has been solved, there is a problem with my original dataset, thank you very much for your help! !！
